services:
  n8n-editor:
    image: n8nio/n8n:1.114.3
    container_name: n8n-editor-ftr
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_paulo
      - TZ=America/Sao_paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      ## Postgres
      - DB_TYPE=postgresdb 
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      ## Queeue mode
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - OFFLOAD_MANUAL_EXCUTIONS_TO_WORKERS=true
      ## webhook
      - WEBHOOK_URL=https://6901-186-192-96-36.ngrok-free.app
    networks: 
      - n8n-ftr
    depends_on:
      - postgres
      - redis
    restart: always

  n8n-worker:
    image: n8nio/n8n:1.114.3
    command: worker
    ports:
      - "5679:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_paulo
      - TZ=America/Sao_paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      ## Postgres
      - DB_TYPE=postgresdb 
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      ## Queeue mode
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - OFFLOAD_MANUAL_EXCUTIONS_TO_WORKERS=true
      ## webhook
      - WEBHOOK_URL=https://6901-186-192-96-36.ngrok-free.app
    networks: 
      - n8n-ftr
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    networks: 
      - n8n-ftr
    restart: always
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - n8n-ftr
    volumes:
      - ./redis-data:/data
    restart: always
  
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4041:4040"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: http n8n-editor-ftr:5678
    environment: 
      - NGROK_AUTHTOKEN=31CCnhaI4nmHoW6POx6SrSMQ0CT_5fqWBZsRVbKEknJh7eENQ
    restart: always
    networks:
      - n8n-ftr
    depends_on:
      - n8n-editor

networks:
  n8n-ftr:
    driver: bridge
